<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-M2MH32B" ignored="0" name="Test_test1" tests="1" failures="1" timestamp="18 Mar 2018 09:28:45 GMT" time="0.981" errors="0">
  <testcase name="function1" time="0.028" classname="com.qa.TEST_page.QA_HOME__Test">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.TEST_page.QA_HOME__Test.function1(QA_HOME__Test.java:36)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- function1 -->
</testsuite> <!-- Test_test1 -->
